---
deployment:
  tasks:
    - /opt/cpanel/nodejs-22.17.0/bin/npm install
    - /opt/cpanel/nodejs-22.17.0/bin/npm run build
    - export DEPLOYPATH=/home/xwdzmwic/public_html/
    - /bin/cp -R dist2/* $DEPLOYPATH