---
deployment:
  tasks:
    - echo "🚀 Inizio deploy"
    - pwd
    - ls -la
    - /home/xwdzmwic/nodeenv/nodejs-22.17.0/22/bin/npm install
    - /home/xwdzmwic/nodeenv/nodejs-22.17.0/22/bin/npm run build
    - export DEPLOYPATH=/home/xwdzmwic/public_html/
    - echo "prova"
    - /bin/cp -R dist/* $DEPLOYPATH