---
deployment:
  tasks:
    - /home/xwdzmwic/nodeenv/nodejs-22.17.0/22/bin/npm install
    - /home/xwdzmwic/nodeenv/nodejs-22.17.0/22/bin/npm run build
    - export DEPLOYPATH=/home/xwdzmwic/public_html/
    - cd dist /bin/cp -R / $DEPLOYPATH