name: 🚀 Build & Deploy to Netsons

on:
  push:
    branches:
      - main   # o il branch che usi per la produzione

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Debug (opzionale)
      - name: Show build output
        run: ls -la dist || ls -la build

     
